name: CI&&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Dependent environment
        run: |
          npm i -g @angular/cli
          npm i -g @ionic/cli
          npm i --force
      
      - name: Build
        run: |
          ionic build
      
      - name: Deploy
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: ./www
          remote: ${{ secrets.DEPLOY_ROOT }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATEKEY }}
